### ISSUE TITLE
Trocar categorias por tags

### ISSUE THREAD

**Issue by andrechalom** [marciomr/rss-fb#1]
O sistema hoje está organizado por categorias, dentro das quais ficam as páginas. Assim, cada página pertence a exatamente uma categoria. É preciso inverter essa lógica para criar tags, permitindo mais de uma tag para cada página.

Para isso, precisamos

- [x] Adaptar a base de dados
- Migrar os dados que existem hoje (movido para #6)
- [ ] Criar os novos tags no YAML
- Adaptar a página gerada (charts.html) para usar tags (como??) (movido para #7)
- [x] Adaptar os scripts de modules e populate para inverter a lógica de categorias para tags
- [x] Adaptar os scripts de resultados (no momento, monitor.rb) para usar a lógica de tags

Sobre a adaptação da página, talvez valha a pena tirar a coluna "categoria" do tabelão e fazer algo como um hover pra mostrar os tags de cada site.

**Comment by marciomr** [comment]
Podemos deixar o javascript.rb para depois. Não é o foco no momento. O foco é a interface linha de comando.

**Comment by andrechalom** [comment]
O problema disso é que se a base de dados for adaptada para termos categorias e não tags, o javascript.rb vai simplesmente deixar de funcionar - vai dar mais trabalho pra manter as duas coisas funcionando do que para adaptar o gráfico.

**Comment by andrechalom** [comment]
Versão funcional do script de resultados (monitor.rb) no branch andrechalom/tags. Para encerrar esse issue, precisamos (1) decidir se haverá migração dos dados antigos ou se iniciamos uma base nova no novo servidor e (2) decidir o formato dos gráficos gerados no html. Também preciso que vocês reclassifiquem o arquivo de RSS.yaml para incluir as tags que interessam (fiz uma transposição mais-ou-menos das categorias que existiam).

**Comment by andrechalom** [comment]
A questão de migração dos dados é bastante simples, pq o que é autoritativo sobre os tags é o arquivo RSS.yaml. Toda vez que o populate.rb é rodado, ele atualiza o pertencimento de tags no banco de dados.

**Comment by andrechalom** [comment]
*[esse issue foi migrado para outro repositório]*
