### ISSUE TITLE
Melhorar log de erros

### ISSUE THREAD

**Issue by andrechalom** [marciomr/rss-fb#3]
Log de erros deve ser salvo de forma automatizada. Buscar no log por problemas comuns e tentar resolve-los

**Comment by andrechalom** [comment]
Corrigi alguns feeds no RSS.yaml e encontrei algumas linhas desativadas sem comentários explicativos: Vice, Jornal Nacional, Ultimo Segundo, Conversa Afiada. Porque eles estão desativados?

**Comment by andrechalom** [comment]
Dos logs, estou vendo alguns problemas recorrentes:

- Problemas de encoding (corrigidos em #9)
- Problemas de URL mt comprido (corrigidos em #9)
- Problemas relacionados a conexão de internet (Ponte, por exemplo, dá varios problemas de Timeout ou incorrect header). Não parece ter muita solução a não ser tentar novamente depois.
- Erros de "Some of the aliases requested do not exist" - acredito que isso se dá quando um link é removido do FB ou simplesmente nunca foi compartilhado lá.
- Problemas relacionados a leitura do RSS em si (ver abaixo)
- undefined method `[]' for nil:NilClass - às vezes, a entrada de RSS vem malformada, sem og_object. Não sei qual a melhor forma de proceder aqui.

Os seguintes feeds estavam com problemas no RSS.yaml:
- Vice: desativada explicitamante por @marciomr em 16/04
- Jornal Nacional: dá erro de OAuth em todas as noticias
- Ultimo Segundo: dá 404 no feed, não consegui identificar um rss alternativo
- Conversa Afiada: Está desabilitado no arquivo de configuração, não sei por que motivo.
- Socialista Morena: O site está usando uma proteção contra DDoS que impede nosso acesso
- IstoÉ: corrigido
- PT na Câmara: corrigido
- Lobão entrevista: Redireciona para o Feedburner que dá 404
- Brasil de fato: corrigido (usando um "proxy" do Google News)

**Comment by marciomr** [comment]
- Vice eu desabilitei porque as únicas materias relevantes eram sempre sobre sexo.
- Jornal Nacional, Últimos Segundo e Lobão acho que podemos abandonar formalmente.
- Da Socialista Morena acho que podemos ficar só com a página.
- Conversa Afiada devia estar dando algum problema. Não me lembro qual. Se puder habilitar e verificar eu agradeceria.

**Comment by andrechalom** [comment]
Conversa afiada tem dezenas de entradas que resultam no erro
`OAuthException, code: 2500, message: Cannot specify an empty identifier, x-fb-trace-id: GlTnZBm9qpx`

Isso parece vir do uso de vírgulas no URL, ver http://stackoverflow.com/questions/12163978/facebook-graph-api-returns-error-2500-when-there-are-commas-in-the-id-url

**Comment by andrechalom** [comment]
Usar o feed generator do Google no Brasil de fato não dá certo (pelo menos out of the box), os URLS são gerados usando o news.google:

    W, [2016-07-14T23:06:16.394925 #28793]  WARN -- : Problemas ao inserir no banco de dados. Feed: Brasil de Fato
    W, [2016-07-14T23:06:16.395057 #28793]  WARN -- : URL: http://news.google.com/news/url?sa=t&fd=R&ct2=in&usg=AFQjCNENtJrOHY_LJqLFrCpYj_AL6kI1Sw&clid=c3a7d30bb8a4878e06b80cf16b898331&ei=EEWIV6-ECdDB3gHwmbbADA&url=https://www.brasildefato.com.br/2016/07/08/prisoes-por-ofensas-a-pm-na-internet-atentam-contra-marco-civil-dizem-especialistas/
    W, [2016-07-14T23:06:16.395392 #28793]  WARN -- : undefined method `[]' for nil:NilClass
    W, [2016-07-14T23:06:16.395515 #28793]  WARN -- : populate.rb:71:in `block (3 levels) in <main>'

**Comment by andrechalom** [comment]
Executando por cron o script atual, apenas erros intermitentes de conexão e o erro de "undefined method `[]' for nil:NilClass" (1 ocorrência) estão sendo reportados.
