### ISSUE TITLE
Estudar performance

### ISSUE THREAD

**Issue by andrechalom** [marciomr/rss-fb#4]
Estudar quanto tempo as tarefas demoram para concluir. Quais são os gargalos? É possível melhorar esse tempo otimizando a busca de "URLs canônicas"? Talvez rodar a coleta com ruby-prof?

**Comment by andrechalom** [comment]
No meu computador, o batch de populate está rodando em ~20 min de coleta de entries novas. O que REALMENTE pode demorar é o update. Tem duas coisas a fazer aqui:

1. Parar de atualizar notícias muito antigas
2. Paralelizar o código.

**Comment by marciomr** [comment]
Acho que podemos começar atualizando tudo que foi postado até 72 horas atrás e calcular o tempo total. Se for menos do que 4 horas acho que não precsisamos nos preocupar.

**Comment by andrechalom** [comment]
Meus resultados preliminares da paralelização (vide #10) apontam que a atualização está rodando em ~20 min para cada 24h acumuladas. Com isso, a previsão de tempo total é de 40 min coleta + 20*4 de updates das últimas 96h = 2h de tempo de processamento.

**Comment by andrechalom** [comment]
Com a otimização atual, o código está executando inteiramente em menos de 40 minutos, com uma janela de update de 96 horas.
