### ISSUE TITLE
Página de acesso mais amigável?

### ISSUE THREAD

**Issue by andrechalom** [marciomr/rss-fb#7]
A página do monitor hoje é pouco amigável. Acredito que ela pode ter as seguintes melhorias:

- [ ] Refazer a página HTML com um novo design: mais gráficos (matérias mais compartilhadas "pizza", barras com tags e feeds, Zipf, etc) e apenas as primeiras 50 - 100 principais matérias do período.
- [ ] Página com índice de todas as coletas feitas
- [ ] Navegação (links para o índice, para o site do GPOPAI, para a página de facebook)
- [ ] Paginação usando [esse js](http://stackoverflow.com/questions/19605078/how-to-use-pagination-on-html-tables#19605115)
- [ ] Adaptar a página para o uso da nova base de dados (tags <> feeds <> entries com relações múltiplas)
- [ ] O número de veículos reportados no index.html é o total de entradas descritas no RSS.yaml. Não é nem o total de veiculos "funcionando" nem o número de veículos que publicou alguma matéria no período.
- [ ] Possibilidade de gerar páginas HTML "customizáveis", passando parâmetros como os aceitos pelo monitor.rb
- [ ] Página diz "Compartilhamentos DESDE 17/07/2016", mas não diz "ATÉ 18/07/2016"
- Geração de novas páginas com um intervalo previsível (algo como "toda segunda"?) (**REMOVIDO**)

**Comment by marciomr** [comment]
Gosto das duas primeiras. Tenho dúvidas sobre a terceira. A princípio acho que prefiro gerar conforme sinta a necessidade. Tem dias que acho bom gerar do último dia, tem dia que prefiro gerar da semana toda.

**Comment by andrechalom** [comment]
*[esse issue foi migrado para outro repositório]*
