### ISSUE TITLE
Melhorias gerais

### ISSUE THREAD

**Issue by andrechalom** [marciomr/rss-fb#8]
- [x] Os arquivos "acessórios" style.css, jquery.tablesorter e imagens deveriam estar no controle de versão
- [x] É importante ter um README no repositório, com um mínimo de instrução sobre cada um dos scripts e raketasks. Por exemplo, demorei um tempo para entender que eu precisava gerar o chart.js e depois o html para visualizar o html com o gráfico.
- [x] "cleanup" dos dados coletados: podemos remover o whitespace em volta dos links
- [x] "cleanup" do repositório. não entendi qual o propósito de: chart.rb (não foi trocado pelo javascript.rb?); entries-csv.rb; keyword-count.rb (não está funcionando?); e qual a diferença entre o results.rb e o entries.rb; finalmente, o config/schedule está sendo usado?
- [x] O programa está travando se ele cai em um ciclo infinito de FB.connect() falhando. Precisamos ter um "timeout" de verdade.
- Talvez colocar uma paginação na página html final melhore a navegação?
(http://stackoverflow.com/questions/19605078/how-to-use-pagination-on-html-tables#19605115) (Movido para #7)
- O número de veículos reportados no index.html é o total de entradas descritas no RSS.yaml. Não é nem o total de veiculos "funcionando" nem o número de veículos que publicou alguma matéria no período. (Movido para #7)

**Comment by marciomr** [comment]
O chart.rb foi trocado pelo javascript.rb. Podemos removê-lo.

**Comment by marciomr** [comment]
keyword-count.rb, entries-csv.rb e entries.rb estão todos "deprecated". Podemos remover todos. O schedule foi usado para gerar a crontab. Não precisamos mais dele.

**Comment by marciomr** [comment]
Seria útil usar paginação no html.rb, mas não acho prioritário.

**Comment by marciomr** [comment]
Gostaria que o número de veículos reportado no index.html fosse o número de veículos funcionando. De fato no presente momento não é.
